version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
      - 3000:3000
    network_mode: bridge
  ruby:
    container_name: ruby_project
    build: .
    command: sh -c "bundle install && yarn && rails db:migrate && rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    network_mode: service:postgres
